#!/usr/bin/env bash
# This script transfers files from a client to a server

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

scp_options="-o StrictHostKeyChecking=no"

if [ $# -eq 3 ]; then
    scp $scp_options "$PATH_TO_FILE" "$USERNAME@$IP:~/"
else
    scp $scp_options -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
fi
