#!/usr/bin/env bash
# This script installs nginx on ubuntu server

apt-get update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx restart
