#!/usr/bin/env bash
# This script configures an Nginx server so that /redirect_me redirects to another page

apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello world!" > /var/www/html/index.nginx-debian.html

sed -i "/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default

service nginx restart
