#!/usr/bin/env bash
# This script configures an Nginx server so that /redirect_me redirects to another page

apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello world!" > /var/www/html/index.nginx-debian.html

sed -i "/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default

service nginx restart
