#!/usr/bin/env bash
# This script installs and configures a HAProxy on a server

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load-balance
        bind :80
        bind :8080
        mode http
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
        option forwardfor
        server 274815-web-01 100.25.103.95 check port 80
        server 274815-web-02 100.24.72.43 check port 80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
