#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59

HOURS=0

while [ $HOURS -le 12 ]
do
	echo "Hour:" "$HOURS"
	MIN=1
	while [ $MIN -lt 60 ]
	do
		echo "$MIN"
		((MIN++))
	done
	((HOURS++))
done
